config/routes.rb
Rails.application.routes.draw do
  resources :pioneers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pioneer.rb
class Pioneer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pioneers_controller.rb
class PioneersController < ApplicationController
  before_action :set_pioneer, only: %i[ show edit update destroy ]

  # GET /pioneers or /pioneers.json
  def index
    @pioneers = Pioneer.all
  end

  # GET /pioneers/1 or /pioneers/1.json
  def show
  end

  # GET /pioneers/new
  def new
    @pioneer = Pioneer.new
  end

  # GET /pioneers/1/edit
  def edit
  end

  # POST /pioneers or /pioneers.json
  def create
    @pioneer = Pioneer.new(pioneer_params)

    respond_to do |format|
      if @pioneer.save
        format.html { redirect_to pioneer_url(@pioneer), notice: "Pioneer was successfully created." }
        format.json { render :show, status: :created, location: @pioneer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pioneers/1 or /pioneers/1.json
  def update
    respond_to do |format|
      if @pioneer.update(pioneer_params)
        format.html { redirect_to pioneer_url(@pioneer), notice: "Pioneer was successfully updated." }
        format.json { render :show, status: :ok, location: @pioneer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pioneers/1 or /pioneers/1.json
  def destroy
    @pioneer.destroy!

    respond_to do |format|
      format.html { redirect_to pioneers_url, notice: "Pioneer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pioneer
      @pioneer = Pioneer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pioneer_params
      params.require(:pioneer).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pioneers_helper.rb
module PioneersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWww</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pioneers/_form.html.erb
<%= form_with(model: pioneer) do |form| %>
  <% if pioneer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pioneer.errors.count, "error") %> prohibited this pioneer from being saved:</h2>

      <ul>
        <% pioneer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pioneers/_pioneer.html.erb
<div id="<%= dom_id pioneer %>">
  <p>
    <strong>First name:</strong>
    <%= pioneer.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= pioneer.last_name %>
  </p>

</div>

app/views/pioneers/edit.html.erb
<h1>Editing pioneer</h1>

<%= render "form", pioneer: @pioneer %>

<br>

<div>
  <%= link_to "Show this pioneer", @pioneer %> |
  <%= link_to "Back to pioneers", pioneers_path %>
</div>

app/views/pioneers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pioneers</h1>

<div id="pioneers">
  <% @pioneers.each do |pioneer| %>
    <%= render pioneer %>
    <p>
      <%= link_to "Show this pioneer", pioneer %>
    </p>
  <% end %>
</div>

<%= link_to "New pioneer", new_pioneer_path %>

app/views/pioneers/new.html.erb
<h1>New pioneer</h1>

<%= render "form", pioneer: @pioneer %>

<br>

<div>
  <%= link_to "Back to pioneers", pioneers_path %>
</div>

app/views/pioneers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pioneer %>

<div>
  <%= link_to "Edit this pioneer", edit_pioneer_path(@pioneer) %> |
  <%= link_to "Back to pioneers", pioneers_path %>

  <%= button_to "Destroy this pioneer", @pioneer, method: :delete %>
</div>